const ALL_LAYERS_VERBOSE = false

const APPLICATION_VERBOSE = ALL_LAYERS_VERBOSE || false
const BLOCKCHAIN_VERBOSE = ALL_LAYERS_VERBOSE || false
const PHYSICAL_VERBOSE = ALL_LAYERS_VERBOSE || false
const CHANNEL_VERBOSE = ALL_LAYERS_VERBOSE || false

const BLOCK_VERBOSE = true
const TRANSACTION_VERBOSE = false


const MESSAGE_LIFE_AFTER_ARRIVAL = 2000 //In milliseconds
const MINIMUM_TRANSACTIONS_IN_BLOCK = 5

const DASHBOARD_UPDATE_PERIOD = 1000 //In milliseconds